### ISSUE TITLE
Failure to launch binder examples

### ISSUE THREAD

**Issue by riazarbi** [wlandau/drake-examples#47] opened 2021-01-29 16:38 UTC
Hello, 

When I click the `launch binder` button in the readme, binder fails to launch.

I'm struggling to copy the logs out of the console, but the error is basically that it can't find the raw file for `master/DESCRIPTION` - it's a 404 error. 

I think this is probably related you you switching from `master` to `main` references.

**Comment by riazarbi** [comment] 2021-01-29 16:46
Here is a screenshot

![image](https://user-images.githubusercontent.com/13433911/106302913-362a7000-6262-11eb-8abe-24eb97e35d4f.png)

**Comment by wlandau** [comment] 2021-01-29 23:35
Looks like I broke the [Dockerfile](https://github.com/wlandau/drake-examples/blob/main/.binder/Dockerfile) when I switched the default branch to `main`. Should be fixed in https://github.com/wlandau/drake-examples/commit/d390804b5025d11b92229c7bafc762b0f66df2b9. Please let me know if the issue persists.

**Closed as completed by wlandau** 2021-01-29 23:35 UTC

**Comment by wlandau** [comment] 2021-01-29 23:57
Confirmed fixed now. The image is rebuilt, and I could initialize the RStudio Server instance.

By the way, I recently developed a new package called [`targets`](https://docs.ropensci.org/targets/), the long-term successor to `drake`. It is more robust and easier to use, and it has individual RStudio Cloud workspaces for example projects linked from the documentation.
